### ISSUE TITLE
Multiple store paths for single client

### ISSUE THREAD

**Issue by dlmac** [Storj/dataserv-client#100]
Move the --store_path into the config and allow multiple paths "c:\storj;d:\storj" would have to figure out max_size, but it could be done.

This is not really an issue but I do not see a way to mark it as a requested enhancement.

**Comment by unsystemizer** [comment]
Tags can be assigned by repo owners.

I see this idea as dangerous because on the surface it appears very useful, but it can get tricky: what happens when one of paths (e.g. d:\storj) disappears? 
Should the client have its DB which path holds which shards? Or should it just err and say "Please rebuild all paths"? 

I'm not against this idea, but it should really be handled with either RAID/volume manager *or* multiple instances of dataserv-client (using different `--config_path`'s, each of which would point to a single store path). Otherwise the convenience of this feature will also bring a many issues down the road.

**Comment by dlmac** [comment]
Couldn't the path disappear as it is currently written with one path? I agree that in most cases RAID should handle this, but in my case I have one computer with 6TB raid 0, and a NAS with 6TB raid 0 (mapped to E:\). Not only would this be helpful in this test, but I think the final client should allow multiple paths. A second use case for this would be clients that are merely sharing their extra space (not dedicated farmers) if they have D: and E: with 1TB extra a RAID setup is not feasible.

**Comment by F483** [comment]
Multiple paths are coming soon, its mostly a matter of ui and adding it to the config.

**Comment by super3** [comment]
We don't plan on adding multiple store paths. Instead we recommend running another instance of dataserv-client with the new store path, and a different authentication address. If one of those disks do fail then it will fail independently of the others. 

A guide to do this is here: https://github.com/Storj/dataserv-client/tree/develop#farmer-multi-disc-guide
