### ISSUE TITLE
Client should not require access to SJCX private key

### ISSUE THREAD

**Issue by mtlynch** [Storj/dataserv-client#36]
The server needs a means of authenticating miners to ensure that:
* A remote attacker cannot impersonate other miners to reduce the victim miner's height
* A attacker with access to the victim miner's network traffic (MiTM) cannot modify the miner's messages to the server to tamper with their contracts / reduce their height

Recent potential solutions have been based on authenticating with the user's SJCX private key. This poses several problems:
* If the miner must sign every message, it requires the miner to have access to the SJCX private key, which means that if an attacker compromises a miner, they can control the user's SJCX wallet
* If the miner signs a single message, an attacker can perform replay attacks on a victim miner's messages if they have access to their network traffic (unless the server stores complicated state to try to prevent this)
* Solutions that authenticate based on SJCX public key mean that a single user with multiple miners must use a separate SJCX address for each miner
* Solutions that depend on copying private keys or signing a message with SJCX key are undesirable for usability as they require the user to go through a series of manual steps involving their SJCX private keys to start mining

I propose the following solution:
* On first run, miners automatically generate a new keypair ("mining private key, mining public key") to authenticate to the server / peers. This is invisible to the user.
 * If the user needs to migrate their contracts to a separate server, we provide a documented process of how to move their mining keypair along with their storage data
* Users specify a SJCX payout address for their miner, which they do not need to prove ownership of (mining on behalf of other users is a permitted scenario)
 * (depending on implementation difficulty) There is not a fixed mapping between mining keys and SJCX payout address. Users can dynamically change their SJCX payout address (e.g. "Every Tuesday, I point my miners at SJCX address 1N7a.... to donate a share of my profits to them.")
* Miners authenticate each message to the server by signing the message with a timestamp and their mining private key.
* Multiple miners can specify the same SJCX payout address

**Comment by F483** [comment]
It seems ok to have an explicit payout address that can be a cold wallet. This can be optional (uses the address of hot wif if not given).

Is the payout address currently required anywhere in the client?

**Comment by F483** [comment]
Added an optional --payout_address to use a cold storage wallet as payout_address. If it is not given, it will default to the address of the given wif.

`dataserv-client --wif=<BITCOIN_WALLET> register --payout_address=<BITCOIN_ADDRESS>`

Being able to generate the wif used for authentication would be optimal, but I am currently unsure as to the most secure solution for this.

Maybe generate randomly and save locally, so it persists across calls. Opinions @super3 @mtlynch

**Comment by unsystemizer** [comment]
How about this:
* Broadcast your GnuPG key from Counterwallet (or locally using `pip3 install counterparty-client; counterparty-client broadcast --text="storj KeyID: xxxx`)
* Encrypt your messages to server with your GPG key
* One key pair per dataserv-client instance

There's more dependencies and another app (gpg) to take care of, but the private key for the address doesn't have to be involved in the process. Also key can be invalidated with GnuPG and replaced by making another broadcast. The fact that it involves a small (tx) cost serves as a small barrier against troll farmers who could otherwise generate a lot of churn on the system.

**Comment by mtlynch** [comment]
I'd really like to avoid giving the miner access to any sensitive keys. Ideally the worst thing that can happen if my miner is compromised is no worse than just turning my miner off.

I would like the process to be entirely transparent to the user unless they're doing something unusual like moving their mining contracts to a different machine. So like:

```
$ dataserv-client register <bitcoin address>
-> /api/register/<mining public key>/<bitcoin address>
```
* **Client**
 * First run: dataserv-client generates mining keypair, caches `<BITCOIN_ADDRESS>` locally for subsequent commands
 * Subsequent runs: dataserv-client uses cached keypair and issues a command to the server telling   the server to change the payout address for this miner, updates cached bitcoin address
* **Server**
 * Receives registration message and saves the association of the miner's public key to the  the corresponding payout address

```
$ dataserv-client build
-> /api/height/<mining public key>/<height>
```
Where the message is signed with the mining private key

```
$ dataserv-client poll
-> /api/ping/<mining public key>
```
Ditto, message is signed with the mining private key

When I say "mining keypair" it can be any keypair, so GPG, RSA, etc. Generating a secure keypair shouldn't be an issue on anything except machines with very low entropy and so maybe we offer a way to manually import keys, but I don't think we need to worry about that immediately.

**Comment by F483** [comment]
I see no need for any external crypro protocols GPG, RSA, etc. With bitcoin wifs, address we have fully functioning asymmetric crypto and everything that comes with it.

I working on having the main key generated automatically and saved locally (will use a bip32 wallet), as well as have it securly encrypted.

> Ideally the worst thing that can happen if my miner is compromised is no worse than just turning my miner off.

While that is the ideal chase we should try to achieve, I must point out that it is an impossibility in the long run. We are going to have nodes sharing drive space and transferring files for money and no matter what we do nodes are going to end up with a wallet.

Take for example the file transfer from node alice to node bob.

 - Somehow they discover each other and agree on prices.
 - A file is transferred from alice to bob (payment channel usage).
 - Future interactions omitted.

In the example above it is unclear who would pay who, this can only be found out by market price discovery. It like is that alice would pay bob for the bandwith, but the opposite is also. Bob might be willing to pay alice for traffic if he for example want to meet a peering quota with his isp.

We must come to terms with the fact that every node, regardless of the service they provide/use will require a wallet. We can do things to mitigate this like sending funds to cold storage wallets, but there will have to be a hot wallet on each node for daily use.

**Comment by utdrmac** [comment]
I disagree with the "every node..will require a wallet" statement. The average Joe user will have 1 home computer with some space to share. It is unreasonable to make it any more complicated than asking the end-user three simple questions: "How much do you want to share?, What directory to share from?, What address should receive payments?"

That's it. Plain and simple. Anything beyond that should be handled invisibly to the user. This functionality should also support multiple shares using the same payout address (ie: my computer and my wife's computer). An end-user should NOT be required to have a different SJCX address per sharing system.

K.I.S.S - keep it stupidly simple. @mtlynch 's idea looks great; it accomplishes all the goals of security yet keeps the experience for the end-user, simple. If you want people to adopt this, it must be simple. WIFs and wallets are too much for the average end-user and providing private keys to any software will deter the security conscious people away.

The code already exists to create a priv/pub key/address within the application. It is only used to handle authentication. My wife's computer, my computer and my work computer would all have different (internal) priv/pub keys/address but payout to the same address.

If I wanted to migrate from my computer to a new NAS I bought for the house, there would exist an (advanced) export feature to print out the WIF from my computer's client and an import feature on NAS client.

If I want to see statistics, I simply paste my payout address in a web form, which searches the polling database for all associated client public keys, and prints out the results per-client.

**Comment by F483** [comment]
>  It is unreasonable to make it any more complicated than asking the end-user three simple questions: "How much do you want to share?, What directory to share from?, What address should receive payments?"
> An end-user should NOT be required to have a different SJCX address per sharing system.

This is valid for the user interface in this specific use case and I would not want it any different. This is however not the only use case and we must account for the others as well. In your case the user may never end up using the wallet or know it exists and that's fine.

**Comment by F483** [comment]
>  autumnalscooter: @fabe I'm not clear on what you're saying. what scenario requires a miner to send payments to someone?

Maybe I need to add some additional context to make things more clear, a simple question should make things more clear.

### Storj is a market for data storage and bandwidth

What is the main feature of storj that other systems do no have? It is not P2P file storage, other systems like bittorrent already do that well.

The main feature that distinguishes storj is that it is a market to buy/sell data storage and bandwidth. And like with all markets for the exchange of goods (in this case bandwidth and storage) we cannot presume direction of payment, this can only be found out by the market itself. Let me gave a few examples.

### You cannot presume the direction of payment in a market

Normally you would presume the provider of a good will receive payment for said good, but there are exceptions to this.

In the real world waste disposal is an example of this, I may pay someone to dispose of my waste or if its of more value they may pay me instead.

### Payment of bandwidth is unclear

A practical example where this may directly apply to store is payment for bandwidth. We cannot presume who will pay for the bandwidth of uploading/downloading data as it is highly dependant on the contracts people have with there ISPs and [peering](https://en.wikipedia.org/wiki/Peering) as well as the business models of the respective server nodes.

Say for example I want to upload a file to a server node. You would expect me to have to pay for the bandwidth, but I can think of two legitimate cases where the server node may even pay me for this.

##### 1. Reverse payment because bandwidth ratio agreements.

Commonly bandwidth usage is not symmetric and so pricing for uploading/downloading will likely be disproportional and reversed depending on where you are. For home connections it is larger download ratios, so downloading would be cheaper and for server this is normal the reverse. From this we can already see that bandwidth pricing will vary high depending on direction and where the machine is located.

Fulfilling bandwidth quotas may cause server nodes to pay clients. It is not uncommon to have ISP contracts assume bandwidth ratios. If these ratios are broken you would have to change to a possible more expensive contract.

How can this happen? Say I have a 50:50 contract with an ISP (so that I must maintain an even upload/download ration within some margin of error). I for some reason I temporally get a unbalanced ration (some file was very popular), I might want to even it out to keep my contract in the long run. This may cause me to temporarily sell of my garbage inbound bandwidth (yes garbage bandwidth exists).

##### 2. Temporally subsidizing service to build reputation. 

No matter what we do, at the end of the day there is going to be some reputation mechanism (which will likely vary depending on what you want, long-term vs short-term storage etc).

If you are a new player in the storj market you may want to sell your services at a loss to build reputation. This may even go as far as paying people to use your service and both storage and bandwidth are affected by this.

#### Conclusion

Storj is a market more then anything else and just like with all markets cannot make to many assumptions. It is up to the market to figure out who pays for what service.

This fundamentally requires all nodes to have a hot wallet (though some may never use it). I will generate a bip32 hd wallet as it has the following useful properties for us.

 - Easy to back up and restore from a since short string.
 - Sub wallets can be created.
 - Multiple instances can share the same wallet (as each one can generate its own sub wallet).
 - A very good implementation exists in pycoin which we can use (via btctxstore).
 - Users can still provide an additional SJCX cold storage address where fund will always (assuming profitability) be sent to, or preferably sent to periodically when they exceed some threshold.

#### PS

Our main concern right now should be the protocol itself. What are the services and how can they be paid for in an automatic decentralized fashion. Then to build a reference client or clients if its need for different actors.

Considering how early we are in the project development I think we are to caught up in little things that do not matter to much right now instead of looking at the big picture. I consider the white paper to be lacking and in need of improvement.

What I think we should be looking at right now.
 - Getting rid of anything centralized, this is going to hurt us more then help us.
 - Churning out lots of experimental prototypes, we are going to make mistakes and we have to do that now instead of later.
  - Git a p2p network running asap that we can connect clients to and monitor/experement with. Linus acceded self hosting and the first commits of git over a weekend. I can do the same if I put my mind to it.

**Comment by unsystemizer** [comment]
> Easy to back up and restore from a since short string.

Well, you don't really need to backup and restore, you just need to provide the pass phrase.
Which brings me to my concern.

> Multiple instances can share the same wallet (as each one can generate its own sub wallet).

What happens if one out of 120 or whatever farms gets busted? The attacker can immediately siphon off funds from all the accounts accessible from this wallet.

I hope the wallet pass phrase shouldn't even be keyed in on the farming system. If private key from a single address were to be used, that would be equally bad for that particular address, but at least it would lessen attack footprint and insulate the rest of addresses in the wallet.

Since any address may require "funding" to pay for stuff the owner could fund them with a small amount of whatever currency they need (e.g. some BTC will be need for dust tx), and should they at any point be lacking sufficient funds the owner could see that in dataserv-client log.

**Comment by F483** [comment]
> Well, you don't really need to backup and restore, you just need to provide the pass phrase.
Yes that's how easy the restore is.

> What happens if one out of 120 or whatever farms gets busted? The attacker can immediately siphon off funds from all the accounts accessible from this wallet.

Yes and I would generally say its a bad Idea to run so many nodes with such large storage amounts on the same wallet.

In the case of running a large farm I would suggest the following solution.

HD wallets let you generate sub wallets that do not know anything about the parent wallet. In this case I would suggest having a root HD wallet that you do not keep safe and generate a sup wallets for each node (we can provide a feature to do this).
You can also generate the a public HD wallet from a node that can only derive public keys, good for a cold storage hd wallet.

This would however provide a different identity for each node on the network, something personally I think is good (no one need to know how many nodes I run for privacy reasons). If you however wish to associate them all for some reason (likely reputation related), maybe we can provide a feature to sign the address we use for the nodes identity/authentication with the root identity.

With the above configuration we would have a setup where each node is isolated and optionally associated with a master identity. To reduce risk of loss, having a cold storage address where earned funds are sent to periodically is the obvious solution. That way if one node is compromised you only loose the small amount of operational cash.

In summary:
 - Each node has a HD wallet for daily use.
 - One of the wallet keys is use as the node identity/authentication.
 - The wallet can be generated from and signed by a master wallet.

That would leave us with a config (best encrypted locally) of the following format.

    {
        "wallet": {
             "master_secret": "111byte hwif",
             "cold_storage": { # we can send excess funds to
                 "hwifs" : ["111byte public hwif"] # public only HD wallet nodes (could even be the public node of the master wallet)
                 "addresses" : [], # loose bitcoin addresses
             }
         },
         "payout": {
             "threshold": 0, # anything above that is sent to cold storage
             "interval": 0 # interval at which we send to cold storage
         },
         signatures: [] # signatures of this wallets identity/authentication address, to associate with a master identity
    }

It would be very easy to write a simple script that generates arbitrary configs for all server farm nodes in a deterministic way so that all you need is one master secret to provide one master secrete as input.

**Comment by unsystemizer** [comment]
What bothers me slightly is that while one could want to own a bunch of addresses, there will be others who would like to own as few as possible (say one per "store" (directory), aka the minimum number) because otherwise one must monitor and fund (with dust amounts of BTC, maybe SJCX) many addresses, which is time consuming and (slightly) increases costs of sending to and sweeping from these addresses as they get used, discarded, etc. 
Maybe that can be scripted, but that means more work. Existing client (counterparty-cli) can use a remote trusted server and maybe using it would be an option for "professional" farmer because they could easily script these operations (`counterparty-client --config-file [farm-a.conf] broadcast|send`), but ideally there would be just one way that would cover all scenarios.

OT: I wonder whether 2-2 or 2-3 multisig (local address + master wallet address + payout address) could make this approach more resistant to theft?

**Comment by F483** [comment]
Yes we will have to work the details of that out over time. Funding nodes shouldn't be a problem if they are profitable (the most likely case as unprofitable nodes are likely to be deactivated). But if someone node operate unprofitable and must be subsidized, this could be easily automated as well, if requesting a donation address is part of the protocol (not a bad idea in general).

In the long run having a separate software to manager and monitor to run server farms with many nodes is desirable, but not a the moment. Having a good reference client for a single node is more important.

Note that the HD wallets that can generate sub wallets play into this scheme. You could start out with a single node and as you grow create sub nodes from its wallet. Eventually you could take the root node offline and use its root wallet to manage all the sub nodes remotely. It can after all generate all the sub wallets and key of each node, but the nodes themselves remain isolated.

**Comment by super3** [comment]
@mtlynch This is more or less implemented and on its way to being released in the next version. The client will be given a WIF or generate one for the user. Currently this will be used for authentication only, and no funds will or should be stored with that keypair. 

User will specify their payout address, which should contain 10k SJCX. That private key will never be exposed to the client. If we do indeed need to handle money on the client they we will revisit this issue.

**Comment by mtlynch** [comment]
Great thanks!
