### ISSUE TITLE
dataserv-client does not automatically switch to poll mode after building has finished

### ISSUE THREAD

**Issue by nuketronik** [Storj/dataserv-client#41]
The client does not automatically switch to polling and does not continue to poll after building has finished. The client stops after building has finished and appears offline.
The client should automatically switch to polling mode and continute to poll after building has finished.

**Comment by unsystemizer** [comment]
Please do not add this "feature".
Or if you accept it, I hope `--disable-autopoll build`will be an option.

**Comment by utdrmac** [comment]
+1 for this. Allows people to start builds and go to sleep knowing that when the build completes it will immediately start polling.

**Comment by unsystemizer** [comment]
That doesn't make any sense. 
Build is not related to poll and should remain separate.
If you want to build & poll, run `dataserv-client build && dataserv-client poll`.

Instead you want to bloat the client with unnecessary features and make lives miserable for those who want to use the client the way it's supposed to be used (run `build` to build, run `poll` to poll).
If `--disable-autopoll` isn't made available (according to some on Slack it seems the current behavior, by the way), then anyone who does not want to build & poll will have to stay up to prevent the client from automatically polling after (or while) build is finished.

**Comment by utdrmac** [comment]
It also doesn't make any sense why would you ever start a build and NOT want to start polling right away. To make everyone happy, how about 3 separate commands: `build`, `poll` and `buildnpoll`

**Comment by unsystemizer** [comment]
It seems the build command starts polling by itself, in which case this "feature" unfortunately already exists and this issue could be closed (and those of us who don't like it would have to create a firewall rule to block polling while we're rebuilding).

**Comment by CaptainSkywave** [comment]
As @utdrmac suggests, I too think it's OK that the build automatically polls while building, and I would think it would be obvious that you want to continue polling after build is completed (aka: revenue), so AFAI am concerned I would welcome an auto-polling to trigger when build is done.
It should be informed that polling runs together with the build process, via an interface/client menu, where you select your choice via an interface/command, or similar.

**Comment by CobraX03** [comment]
I agree that they should be kept as separate processes. To have it poll while building is a nice option just to see the height rise via the web statistics but I had the process crash and that was it. I would rather have just ran a separate poll command in case something like that happened. (I did not think to do that as it was polling and working fine)

**Comment by super3** [comment]
Building IS already polling as it increases its height. The main concern is that when rebuilding it takes quite a long time to parse through the original files(because we do a poll in between). So poll and build will be made into one command, and recheck will be pretty fast in the next version. 

So this is what should happen. You can run build and it will automatically poll at the end. If you already have the files built, and you don't want it to check it run ``--skip-check`` and it will go straight to polling.

**Comment by unsystemizer** [comment]
> Building IS already polling as it increases its height. 

I consider that to be a bug. 
If I am farming data on System A (height 20000) while priming System B, the moment I start `build` on System B, my 20K of shards on System A instantly become worthless. 

In production, I still wouldn't want `build` to mean "build and poll".

In production there will be a need for occasional shard migration to new storage, and then a quick restart. to minimize downtime. 
With `poll` and `build` separate that would be easy, but by making `build` contain various unrelated and hidden functionality that can't be controlled, it will cause confusion and token loss.

**Comment by nrenich** [comment]
I have run into this myself while building to a new 10TB array on one of my addresses. In fact, I've held off on moving to 20TB because of it. I'm kind of waiting to see what a new version will bring. I've had some concerns that I would not get credit for my efforts to date, jumping from 4TB to 6TB, 10TB, etc over the last couple weeks. It would have sucked if somewhere in the process a snapshot would be taken and I would have received a lower proportion of rewards even though I've had impeccable up-time with what had been built to date. 

It's just a suggestion but maybe a "max height" record could be kept on the web server side per address and as long as your "Last Seen" is within 12/24 hours, you would not loose position. I realize this is just for our testing phase, and necessities like this won't likely be needed for final product.

**Comment by unsystemizer** [comment]
@nrenich glad to see people are recognizing issues with the current approach. 
"Max height": more coding could be done to prevent issues from the "build & poll" feature, or the build command could be made to work like it's supposed to (just build and not poll) and the problem would be solved.

**Comment by nrenich** [comment]
Yes I can see both sides and the need for multiple command line switches. At this point in the testing, I believe it would be good to have the option of Build Only, Poll Only, and Build & Poll. That would help new farmer and older farmers. 

I don't know how much this will be an issue long term, especially when the day comes when we can have multiple size drives/arrays associated with one build address. (A "farm" vs. a "rig") Once we get past the competition phase of just getting as much online to grab reward share, these option might be irrelevant.

**Comment by F483** [comment]
Added simple start command. It's fully automatic for users wishing a simple turnkey solution. This will run all functions automatically with the most sane defaults and as little user interface as possible.

Right now this will register if needed, build and then poll. Going forward I intend this being a turnkey solution for users wishing to rent out drive space, so all that is need is to configure the config and then start.

Example usage:

    dataserve-client config --set_payout_address=<YOUR_ADDRESS>
    dataserve-client --store_path=<PATH> --max_size=5G start

See https://github.com/Storj/dataserv-client/commit/4e1380f60de47df0e9e78d25cef49560fd984ffc

**Comment by F483** [comment]
Renaming it to farm before so its more clear what its for.
