### ISSUE TITLE
When the client updates the payout address, it should also be updated server side.

### ISSUE THREAD

**Issue by F483** [Storj/dataserv-client#55]
We have no server api call to update the payout address!

**Comment by super3** [comment]
We want to think of a payout address with 10k SJCX in it as an identity. For simplicity and for that reason, users will not be able to change their payout address. They will have to delete their identity and start over, but they can still use the same shards. 

This would add a ton of complexity to the code, and open up the possibility of some malicious behavior because the payout addresses would be mutable.
